apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vardidze-staging
  region: eu-central-1 

nodeGroups:
  - name: vardidze
    instanceType: t2.large
    desiredCapacity: 1
    volumeSize: 40
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
