apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: zaytoon-prod
  region: eu-central-1 

nodeGroups:
  - name: zaytoon
    instanceType: t2.large
    desiredCapacity: 3
    volumeSize: 40
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
