apiVersion: v1
kind: Secret
metadata:
  name: secret-ewa-back-{{ .Values.entity }}
  labels:
    environment: {{ .Values.typeEnvironment }}
type: Opaque
data:
  ALLOWED_HOSTS: {{ .Values.envVariablesBack.ALLOWED_HOSTS | b64enc | quote }}
  SECRET_KEY: {{ .Values.SECRET_KEY | b64enc | quote }}
  POSTGRES_DB: {{ .Values.envVariablesBack.POSTGRES_DB | b64enc | quote }}
  POSTGRES_HOST: {{ .Values.envVariablesBack.POSTGRES_HOST | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.envVariablesBack.POSTGRES_PORT | b64enc | quote }}
  POSTGRES_USER: {{ .Values.envVariablesBack.POSTGRES_USER | b64enc | quote }}
  POSTGRES_NAME: {{ .Values.envVariablesBack.POSTGRES_NAME | b64enc | quote }}
  REDIS_HOST: {{ .Values.envVariablesBack.REDIS_HOST | b64enc | quote }}
  AWS_S3_REGION_NAME: {{ .Values.envVariablesBack.AWS_S3_REGION_NAME | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  BUCKET_NAME: {{ .Values.BUCKET_NAME | b64enc | quote }}
  AWS_S3_CUSTOM_DOMAIN: {{ .Values.envVariablesBack.AWS_S3_CUSTOM_DOMAIN | b64enc | quote }}
  firebase_creds_json: {{ toJson .Values.firebase_creds_json | b64enc | quote }}
  FLOWER_USER: {{ .Values.envVariablesBack.FLOWER_USER | b64enc | quote }}
  FLOWER_PASSWORD: {{ .Values.FLOWER_PASSWORD | b64enc | quote }}
  ENVIRONMENT: {{ .Values.envVariablesBack.ENVIRONMENT | b64enc | quote }}
