apiVersion: v1
kind: Secret
metadata:
  name: secret-strapi-{{ .Values.entity }}
  labels:
    environment: {{ .Values.typeEnvironment }}
type: Opaque
data:
  APP_KEYS: {{ .Values.APP_KEYS | b64enc | quote }}
  API_TOKEN_SALT: {{ .Values.API_TOKEN_SALT | b64enc | quote }}
  ADMIN_JWT_SECRET: {{ .Values.ADMIN_JWT_SECRET | b64enc | quote }}
  TRANSFER_TOKEN_SALT: {{ .Values.TRANSFER_TOKEN_SALT | b64enc | quote }}
  JWT_SECRET: {{ .Values.JWT_SECRET | b64enc | quote }}
  POSTGRES_NAME: {{ .Values.envVariablesStrapi.POSTGRES_NAME | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc | quote }}
  HOST: {{ .Values.envVariablesStrapi.HOST | b64enc | quote }}
  PORT: {{ .Values.envVariablesStrapi.PORT | b64enc | quote }}
  DATABASE_CLIENT: {{ .Values.envVariablesStrapi.DATABASE_CLIENT | b64enc | quote }}
  POSTGRES_HOST: {{ .Values.envVariablesStrapi.POSTGRES_HOST | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.envVariablesStrapi.POSTGRES_PORT | b64enc | quote }}
  POSTGRES_USER: {{ .Values.envVariablesStrapi.POSTGRES_USER | b64enc | quote }}
