# Default values for zaytoon-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main-latest"

service:
  type: ClusterIP
  port: 80

entity: prod

ingress:
  host: k8s.zaytoon.io 

envVariablesBack:
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: postgres
  POSTGRES_HOST: zaytoon-k8s-staging.cbykyy4uil8d.eu-central-1.rds.amazonaws.com
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_NAME: zaytoon_back
  AWS_S3_REGION_NAME: ru-1
  AWS_S3_CUSTOM_DOMAIN: https://s3.timeweb.com

envVariablesStrapi:
  POSTGRES_NAME: zaytoon_strapi
  HOST: "0.0.0.0"
  PORT: "1337"
  DATABASE_CLIENT: postgres
  POSTGRES_HOST: zaytoon-k8s-staging.cbykyy4uil8d.eu-central-1.rds.amazonaws.com
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres

typeEnvironment: prod
