name: deploy

on:
  push:
    branches:
      - main

env:
  EKS_CLUSTER_NAME: zaytoon-prod 
  AWS_REGION: eu-central-1


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: trigered helm
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            echo "${{ secrets.CREDENTIALS_PROD_K8S }}" > credentials.yaml
            helm upgrade zaytoon-prod -f zaytoon-chart/values-prod.yaml -f credentials.yaml zaytoon-chart/
