name: deploy

on:
  push:
    branches:
      - staging

env:
  EKS_CLUSTER_NAME: zaytoon-staging 
  AWS_REGION: eu-central-1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@master

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{env.AWS_REGION}}

      # - name: Update kube config
      #   run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      # - name: trigered helm
      #   uses: WyriHaximus/github-action-helm3@v3
      #   with:
      #     exec: |
      #       echo "${{ secrets.CREDENTIALS_STAGING_K8S }}" > credentials.yaml
      #       helm upgrade zaytoon-staging -f zaytoon-chart/values-staging.yaml -f credentials.yaml zaytoon-chart/
